Tests if file exists before attempting curl upload

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -253,10 +253,13 @@ deploy-benchflow-dsl:
           echo "Creating version for branch..."
           curl -v -u$BINTRAY_ADMIN_USERNAME:$BINTRAY_API_KEY -H "Content-Type: application/json" -d '{"name": "'"$WERCKER_GIT_BRANCH"'", "desc": "'"$WERCKER_GIT_BRANCH"'"}' "https://api.bintray.com/packages/$BINTRAY_USERNAME/$BINTRAY_USERNAME-maven/$ARTIFACT_NAME/versions" | jq .
           echo ""
+          
+          # Check if the expected file exists
+          if [ ! -f $WERCKER_SOURCE_DIR/$ARTIFACT_NAME.jar ]; then
+              echo "File not found: $WERCKER_SOURCE_DIR/$ARTIFACT_NAME.jar"
+              exit 1
+          fi
 
-          ls $WERCKER_SOURCE_DIR/
-
-          #TODO: make curl: Can't open fail the script, so the delivery fails
           #NOTE: The output of the previous pipeline is in the source of the next pipeline
           echo "Uploading artefact for commit..."
           curl -v -T $WERCKER_SOURCE_DIR/$ARTIFACT_NAME.jar -u$BINTRAY_ADMIN_USERNAME:$BINTRAY_API_KEY "https://api.bintray.com/content/$BINTRAY_USERNAME/$BINTRAY_USERNAME-maven/$ARTIFACT_NAME/$WERCKER_GIT_BRANCH_$CUSTOM_VERSION_TAG/$ARTIFACT_NAME_$WERCKER_GIT_BRANCH_$CUSTOM_VERSION_TAG.jar?publish=1&override=1" | jq .
